### ISSUE TITLE
Request ubuntu 20.04 not working

### ISSUE THREAD

**Issue by ChaosJesus** [vanita5/Lastfm-Twitter-Lyrics-Bot#1]
Hello. I had to setup my server fresh and now i have the Problem that python2.7-pip can't install the correct version of requests and the Installation of lyricsfetch does not work. Is there a workaround?

**Comment by eliah-w** [comment]
This software is 6 years old and I don't even know if it's still compatible with the used APIs or correctly parsing lyrics.
Sorry, but I'm afraid you have to try to fix this yourself.
